# Generated by Django 5.2.6 on 2025-11-09 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_transaction_module', '0002_inventorytransaction_processed_and_more'),
        ('location_module', '0001_initial'),
        ('product_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('OUT', 'Out (Loaned)'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='OUT', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_at', models.DateTimeField(blank=True, null=True)),
                ('actual_returned_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_created_by', to=settings.AUTH_USER_MODEL)),
                ('outgoing_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_outgoing', to='inventory_transaction_module.inventorytransaction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_records', to='product_module.product')),
                ('return_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_return_sections', to='location_module.section')),
                ('return_shelf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_return_shelves', to='location_module.shelf')),
                ('return_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_return', to='inventory_transaction_module.inventorytransaction')),
                ('return_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_returns', to='location_module.warehouse')),
                ('source_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_outgoing_sections', to='location_module.section')),
                ('source_shelf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_outgoing_shelves', to='location_module.shelf')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_outgoing', to='location_module.warehouse')),
            ],
            options={
                'verbose_name': 'Borrow Record',
                'verbose_name_plural': 'Borrow Records',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['reference_no'], name='borrow_modu_referen_83c0aa_idx'), models.Index(fields=['borrower'], name='borrow_modu_borrowe_f44f64_idx')],
            },
        ),
    ]
