# Generated by Django 5.2.6 on 2025-11-09 06:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_transaction_module', '0002_inventorytransaction_processed_and_more'),
        ('location_module', '0001_initial'),
        ('product_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=50)),
                ('transport_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segment_outgoing', to='location_module.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_segments', to='product_module.product')),
                ('related_inventory_transactions', models.ManyToManyField(blank=True, related_name='movement_segments', to='inventory_transaction_module.inventorytransaction')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segment_incoming', to='location_module.warehouse')),
            ],
            options={
                'verbose_name': 'Movement Segment',
                'verbose_name_plural': 'Movement Segments',
                'ordering': ['movement', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='MovementCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('VEHICLE_RENT', 'Vehicle Rent'), ('DRIVER_FEE', 'Driver Fee'), ('FUEL', 'Fuel Cost'), ('INSURANCE', 'Insurance'), ('CUSTOMS', 'Customs Duty'), ('HANDLING', 'Loading/Unloading'), ('OTHER', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='movement_module.movementsegment')),
            ],
            options={
                'verbose_name': 'Movement Cost',
                'verbose_name_plural': 'Movement Costs',
            },
        ),
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=128, unique=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound'), ('TRANSFER', 'Transfer')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False, help_text='True when movement processed into inventory transactions and stock updated')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_movements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_movements', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='location_module.warehouse')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='location_module.warehouse')),
            ],
            options={
                'verbose_name': 'Product Movement',
                'verbose_name_plural': 'Product Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='movementsegment',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='movement_module.productmovement'),
        ),
    ]
