# Generated by Django 5.2.6 on 2025-11-09 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_transaction_module', '0001_initial'),
        ('location_module', '0001_initial'),
        ('product_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type', 'product'], name='inventory_t_transac_5d6143_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['reference_number'], name='inventory_t_referen_70e6c6_idx'),
        ),
    ]
