# Generated by Django 5.2.6 on 2025-11-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_module', '0001_initial'),
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location_module.section')),
                ('shelf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location_module.shelf')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_module.warehouse')),
            ],
            options={
                'unique_together': {('product', 'warehouse', 'section', 'shelf')},
            },
        ),
    ]
