# Generated by Django 5.2.6 on 2025-11-09 06:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_transaction_module', '0002_inventorytransaction_processed_and_more'),
        ('location_module', '0001_initial'),
        ('product_module', '0001_initial'),
        ('stock_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.DecimalField(decimal_places=4, max_digits=18)),
                ('prev_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('new_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock Ledger Entry',
                'verbose_name_plural': 'Stock Ledger Entries',
            },
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'warehouse'], name='stock_modul_product_e39efa_idx'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='stock_module.stock'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_transaction_module.inventorytransaction'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['stock', 'created_at'], name='stock_modul_stock_i_ab362f_idx'),
        ),
    ]
